### PR TITLE
fix: print indent once per level by default

### LINKED ISSUE #405: astprinter: PrintIndent applies indentation twice
Check out the following snippet: https://go.dev/play/p/FkEAZlnbd-E

The indentation is set to a single tab (`"\t"`), however, the printed output uses two tabs for indentation. Only one is expected.

---

```go
package main

import (
	"fmt"
	"os"

	"github.com/wundergraph/graphql-go-tools/pkg/ast"
	"github.com/wundergraph/graphql-go-tools/pkg/astparser"
	"github.com/wundergraph/graphql-go-tools/pkg/astprinter"
	"github.com/wundergraph/graphql-go-tools/pkg/operationreport"
)

const graph = `
	{ foo bar(id: "123") }
`

func main() {
	parser := astparser.NewParser()
	doc := ast.NewDocument()
	doc.Input.ResetInputBytes([]byte(graph))

	report := operationreport.Report{}
	parser.Parse(doc, &report)

	if report.HasErrors() {
		fmt.Println(report.Error())
		return
	}

	if err := astprinter.PrintIndent(doc, doc, []byte("\t"), os.Stdout); err != nil {
		fmt.Println(err)
	}

	fmt.Println()
}
```

Output:
```graphql
{
		foo
		bar(id: "123")
}
```

### PR DESCRIPTION
**Pull request by ysmolski**
For v1 and v2 this fixes the default behaviour of the PrintIndent and
PrintStringIndent functions of astprinter. Instead of printing indent
twice for every depth level, it prints it once per level.

The fix does not alter output for other parts, golden tests
are intact. Tests were modified by passing correctly sized indent.

Fixes #405

### CODE REVIEW

**Comment by devsergiy** [comment]
Hi @ysmolski 

thanks for the PR

v1 considered as unmaintained
We would appreciate it if you could port these changes to v2

Thanks
Wundergraph Team!

File: pkg/ast/ast_description.go [hunk 1]
```diff
@@ -45,7 +45,6 @@ func (d *Document) PrintDescription(description Description, indent []byte, dept
 				skippedWhitespace += 1
 				continue
 			case runes.SPACE:
-				skippedWhitespace += 0.5
```
Comment (devsergiy) [inline pkg/ast/ast_description.go:48]: does it have any consequences for the printing of multiline descriptions?

File: pkg/astprinter/astprinter.go [hunk 2]
```diff
@@ -12,12 +12,14 @@ import (
 
 // Print takes a document as well as a definition (optional) and prints it to the io.Writer.
 // The definition is only necessary in case a GraphQL Operation should be printed.
+// Print uses four spaces as indentation.
```
Comment (devsergiy) [inline pkg/astprinter/astprinter.go]: Does the comment reflect the behavior? Print should by default print unintended document

File: pkg/federation/schema_test.go [hunk 3]
```diff
@@ -10,6 +11,7 @@ import (
 func TestSchemaBuilder_BuildFederationSchema(t *testing.T) {
 	actual, err := BuildFederationSchema(baseSchema, serviceSDL)
 	assert.NoError(t, err)
+	fmt.Println(actual)
```
Comment (devsergiy) [inline pkg/federation/schema_test.go]: debug code?

**Review by devsergiy — CHANGES_REQUESTED** [review]

File: pkg/ast/ast_description.go (hunk 1 above)
Comment (ysmolski) [reply pkg/ast/ast_description.go:48]: If I keep this line it breaks the following golden test. It tries to add two unneeded spaces. I might look into this whole function with skipping whitespace, though. I have not spotted any test with tabs too...
```
--- FAIL: TestSchemaBuilder_BuildFederationSchema (0.00s)
    schema_test.go:13: Result did not match the golden fixture. Diff is below:

        --- Expected
        +++ Actual
        @@ -73,4 +73,4 @@
             Explains why this element was deprecated, usually also including a suggestion
        -    for how to access supported similar data. Formatted in
        -    [Markdown](https://daringfireball.net/projects/markdown/).
        +      for how to access supported similar data. Formatted in
        +      [Markdown](https://daringfireball.net/projects/markdown/).
             """
```

File: pkg/astprinter/astprinter.go (hunk 2 above)
Comment (ysmolski) [reply pkg/astprinter/astprinter.go]: Oh. My bad. Removing this, print does not use indent at all!

File: pkg/federation/schema_test.go (hunk 3 above)
Comment (ysmolski) [reply pkg/federation/schema_test.go]: Yes, removing it now

**Comment by ysmolski** [comment]
> thanks for the PR
> v1 considered as unmaintained We would appreciate it if you could port these changes to v2

All fixes are done. v2 was patched as well.

**Review by devsergiy — APPROVED** [review]
